image: python:3.7

stages:
  - build
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

Static Type check:
  stage: types
  script:
    - poetry run python main.py

Deploy to GitHub Pages:
  stage: deploy
      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: template
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

